---
- name: "Ensure python3-jmespath package is present"
  tags:
    - always
  ansible.builtin.package:
    state: present
    name: python3-jmespath

- name: "Populate"
  tags:
    - always
  ansible.builtin.set_fact:
    supported_os: "{{ supported_platforms | json_query('[].name') }}"

- name: "Check os support"
  tags:
    - always
  ansible.builtin.assert:
    that:
      - ansible_distribution in supported_os
    fail_msg: "Your OS {{ ansible_distribution }} is not supported"

- name: "Populate supported releases"
  tags:
    - always
  ansible.builtin.set_fact:
    supported_versions: "{{ (supported_platforms | selectattr('name', 'match', ansible_distribution) | list | first).versions }}"

- name: "Assert support"
  tags:
    - always
  ansible.builtin.assert:
    that:
      - ansible_distribution_version|int in supported_versions|list
    fail_msg: "Your distribution {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_distribution_release }}) is not supported"

- name: 'Hardware requirements'
  when: platform_requirement is defined
  block:
    - name: 'Assert memory requirements'
      when: platform_requirement.memory is defined
      tags:
        - always
      ansible.builtin.assert:
        that:
          - ansible_memtotal_mb|int >= {{ platform_requirement.memory }}
        fail_msg: 'Your platform {{ ansible_fqdn }} doesn’t meet memory requirements ({{ platform_requirement.memory }})'

    - name: 'Assert CPU requirements'
      when: platform_requirement.cpu is defined
      tags:
        - always
      ansible.builtin.assert:
        that:
          - ansible_processor_nproc|int >= {{ platform_requirement.cpu }}
        fail_msg: 'Your platform {{ ansible_fqdn }} doesn’t meet CPU requirements ({{ platform_requirement.cpu }})'
