---
- name: "Distribution validator"
  ansible.builtin.assert:
    that:
      - ansible_distribution in support.keys()|list
    fail_msg: "Your {{ ansible_distribution }} is not supported"

- name: "Version validation"
  ansible.builtin.assert:
    that:
      - ansible_distribution_major_version in support[ansible_distribution]
    fail_msg: "Your {{ ansible_distribution }} version {{ ansible_distribution_major_version }} is not supported"
