---
- name: Prepare
  hosts: all

  tasks:
    - name: ensure python pip is present
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: ensure jmespath module is present
      ansible.builtin.pip:
        name: jmespath
