---
- name: Prepare
  hosts: all

  tasks:
    - name: ensure python pip is present
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: ensure jmespath module is present
      ansible.builtin.pip:
        name: jmespath
