---
name: CI Status
on: [create, push, pull_request, release]

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - almalinux8
          - debian10
          - debian11
          - rocky8
          - ubuntu1804
          - ubuntu2004
          - ubuntu2104
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Setup python
        uses: actions/setup-python@v1
      - name: Install required python module
        uses: BSFishy/pip-action@v1
        with:
          requirements: "https://gist.githubusercontent.com/vfricou/456bebc73df55c1dbf5351c808debaa1/raw/d4f06a57c46e628bf64a1a095a287bbf276f9864/ansible-latest.txt"
      - name: Perform molecule full tests
        working-directory: vfricou/ansible_role_user_password_update
        run: molecule test --scenario-name ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
